[package]
name = "zz-p2p"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.40", features = ["full"] }
clap = { version = "4.2", features = ["derive"] }
anyhow = "1.0"
sha1 = "0.10.6"
base64 = "0.22.1"

[dev-dependencies]
cargo-llvm-cov = "0.6.21"
cargo-nextest = "0.9.114"
